version: "3.7"
services:
  stunnel:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    network_mode: host
    volumes:
      - /etc/ssl/blankon:/certs
      - ./stunnel.conf:/stunnel.conf
    command: sh -c "stunnel /stunnel.conf"
