version: "3.7"
services:
  ${site-a}:
    build:
      context: ./
      dockerfile: Dockerfile
    image: ${site-a}
    container_name: ${site-a}
    restart: unless-stopped
    network_mode: bridge
    volumes:
      - ../certs:/certs
      - ./stunnel.conf:/stunnel.conf
    ports:
      - '6371:6379'
    command: sh -c "redis-server --requirepass ${mypassword} && stunnel /stunnel.conf"
